backend/urls.py
from django.contrib import admin
from django.urls import path, include

# media upload
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('covid.urls', 'covid'), namespace='covid')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('detail/<slug:slug>', views.news_detail, name="detail"),
    path('categories/<int:id>/', views.news_category, name="category"),
    path('categories/<int:id>/<slug:slug>', views.news_category_detail, name="category_detail"),
]

news/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html

# Create your models here.
class TypeNews(models.Model):
    type_news = models.CharField("Type of News", max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Type of News"
        
    def __str__(self):
        return self.type_news
    

class News(models.Model):
    code = models.IntegerField("Code of News", unique=True)
    name = models.CharField("Name of News", max_length=255, blank=False, null=False)
    slug = models.SlugField(max_length=255)
    img = models.ImageField(upload_to="imgNews", verbose_name="Images News", null=True, blank=True)
    title = models.TextField("Head Title")
    imgC1 = models.ImageField(upload_to="imgNews", null=True, blank=True)
    content1 = models.TextField(blank=True, null=True)
    imgC2 = models.ImageField(upload_to="imgNews", null=True, blank=True)
    content2 = models.TextField(blank=True, null=True)
    imgC3 = models.ImageField(upload_to="imgNews", null=True, blank=True)
    content3 = models.TextField(blank=True, null=True)
    imgC4 = models.ImageField(upload_to="imgNews", null=True, blank=True)
    content4 = models.TextField(blank=True, null=True)
    type_news = models.ManyToManyField(TypeNews, verbose_name="Type of News", blank=False)
    published = models.BooleanField(blank=False, null=False, default=1)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "News"

    def __str__(self):
        return self.name
    
    def show_img(self):
        if self.img :
            return format_html('<img src={} height="40px">'.format(self.img.url))
        return ''
    show_img.allow_tags = True
    show_img.short_description = "img of news"

news/views.py
from django.shortcuts import render
# import Paginator
from django.core.paginator import Paginator, InvalidPage, PageNotAnInteger, EmptyPage
from news.models import *
# Create your views here.
def home(request):
    news = News.objects.all().order_by('-created')
    type_news = TypeNews.objects.all()

    news_paginator = Paginator(news, 6) # show news 6 items per page
    page_index = request.GET.get('page') # get page you want to access
    print("[page_index] {}".format(page_index))
    try:
        if page_index:
            news = news_paginator.page(page_index)
        else:
            news = news_paginator.page(1)
    except PageNotAnInteger:
        news = news_paginator.page(1)
    except EmptyPage:
        # if page_index over than 'number of news_paginator' then return to 'last of news_paginator' instead
        news = news_paginator.page(news_paginator.num_pages)
    except InvalidPage:
        news = news_paginator.page(1)

    print("[news.number]:\t{}".format(news.number)) # show number of current page

    return render(request, 'news/news.html', {'news':news, 'type_news':type_news})

def news_detail(request, slug):
    news = News.objects.get(slug=slug)
    current_page = request.GET.get('p')

    return render(request, 'news/news_detail.html', {'news':news, 'current':current_page})
    
def news_category(request, id):
    news_cat = TypeNews.objects.get(id=id)
    news = News.objects.filter(type_news=id)

    return render(request, 'news/news.html', {'news_cat':news_cat, 'news':news})

def news_category_detail(request, id, slug):
    news = News.objects.filter(type_news=id, slug=slug)

    return render(request, 'news/news.html', {'news':news})

templates/news/news.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}
{% block title %}News{% endblock title %}

{% block content %}
<div class="card font shadow-sm mb-3">
    <h1 class="text-center card-header">ข่าวสาร</h1>
    <div class="d-flex flex-row flex-wrap justify-content-baseline mt-2 mb-0 px-4">
        <h5 class="m-1">ประเภทข่าว : </h5>
        <a href="{% url 'news:home' %}" class="btn btn-sm btn-secondary mx-2 mb-0 rounded-pill">ทั้งหมด</a>
        {% for cat in type_news.all %}
            <a href="{% url 'news:category' cat.id %}" class="btn btn-sm mx-2 mb-0 rounded-pill {% if cat.id == 1 %} btn-primary{% else %} btn-success {% endif %}">
                {{ cat.type_news|capfirst }}
            </a>
        {% endfor %}
    </div>
    <hr>
    <div class="container">
        <div class="row my-3">

            {# show news #}
            {% for n in news %}
                <div class="col-4 my-2" id="card_news">
                    <a href="{% url 'news:detail' n.slug %}?p={{ news.number }}" class="text-decoration-none text-dark">
                        <div class="card h-100">
                            <img src="{{ n.img.url }}" class="img-fluid card" alt="img-news">
                            <div class="card-body d-flex flex-column justify-content-between">
                                <div>
                                    <p class="card-title text-start">
                                        <b>{{ n.title }}</b>
                                    </p>
                                    <p class="card-text d-flex flex-wrap align-items-center">
                                        <p class="font-weight-bold d-inline">ประเภทข่าว : </p>
                                        {% for i in n.type_news.all %}
                                            <a href="{% url 'news:category' i.id %}" class="btn badge {% if i.id == 1 %}badge-primary{% else %}badge-success{% endif %}">{{ i.type_news }}</a>
                                        {% endfor %}
                                    </p>
                                </div>
                                <p class="card-text">
                                    <small class="text-muted d-block">{{ n.created|naturaltime }}</small>
                                    <a href="{% url 'news:detail' n.slug %}?p={{ news.number }}" class="card-link">อ่านเพิ่มเติม</a>
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>

        {# Pagination Page of News #}
        <div class="row d-flex justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {# previous button #}
                    <li class="page-item {% if news.has_previous != True %}disabled{% endif %}">
                        {# previous_page_number will throw 'None' if not has previous page #}
                        {% if news.previous_page_number != None %}
                            <a class="page-link" href="{% url 'news:home' %}?page={{ news.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
                        {% else %}
                            <a class="page-link" href="{% url 'news:home' %}" tabindex="-1" aria-disabled="true">Previous</a>
                        {% endif %}
                    </li>

                    {# count number of page in news ex. page 1, 2, 3 etc. #}
                    {% for i in news.paginator.page_range %}
                        {# check current of page #}
                        <li class="page-item {% if news.number == i %}active{% endif %}">
                            <a class="page-link" href="{% url 'news:home' %}?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}

                    {# next button #}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'news:home' %}?page=2">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock content %}

templates/news/news_detail.html
{% extends '../base.html' %}

{% load static %}

{% block title %}{{ news.title }}{% endblock title %}

{% block content %}
<div class="card mb-4 border shadow-lg">
    <div class="card-header">
        <h3 class="text-justify">{{ news.title }}</h3>
    </div>
    <div class="card-body">
        <div class="row my-1 py-2">
            <div class="col-12">
                <img src="{{ news.img.url }}" class="img-fluid rounded w-100 mx-auto"><br>
            </div>    
        </div>

        <div class="row my-2 py-2">
            <div class="col">
                <h5 class="card-title font-weight-bold px-4">{{ news.title }}</h5>
                <p class="text-muted px-4">{{ news.created }}</p>
                <hr class="border-bottom shadow-sm">
            </div>
        </div>

        <div class="row mb-2 py-2">
            <div class="col-10 offset-1">
                <p class="card-text text-justify">

                    {# content 1 #}                    
                    <p class="text-justify">{{ news.content1 }}</p>
                    {% if news.imgC1 %} 
                        <img src="{{ news.imgC1.url }}" class="img-fluid card mb-3 w-75 mx-auto" alt="img-content"> 
                    {% endif %}

                    {# content 2 #}
                    <p class="text-justify">{{ news.content2 }}</p>
                    {% if news.imgC2 %} 
                        <img src="{{ news.imgC2.url }}" class="img-fluid card mb-3 w-75 mx-auto" alt="img-content"> 
                    {% endif %}

                    {# content 3 #}
                    <p class="text-justify">{{ news.content3 }}</p>
                    {% if news.imgC3 %} 
                        <img src="{{ news.imgC3.url }}" class="img-fluid card mb-3 w-75 mx-auto" alt="img-content"> 
                    {% endif %}

                    {# content 4 #}
                    <p class="text-justify">{{ news.content4 }}</p>
                    {% if news.imgC4 %} 
                        <img src="{{ news.imgC4.url }}" class="img-fluid card mb-3 w-75 mx-auto" alt="img-content"> 
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <a href="{% url 'news:home' %}?page={{ current }}" class="btn btn-info btn-block">ย้อนกลับ</a>
            </div>
        </div>

    </div>
</div>
{% endblock content %}