backend/urls.py
from django.contrib import admin
from django.urls import path, include

# media upload
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('covid.urls', 'covid'), namespace='covid')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

covid/urls.py
from django.urls import path
from covid import views

urlpatterns = [
    path('', views.index, name = 'home'),
    path('predict', views.predict, name='predict'),
    path('saveresult', views.saveResult, name="saveresult"),
    path('confirm', views.confirm, name='confirm'),
    path('assessment', views.assessment, name='assessment'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name="profile"),
    path('profile/edit', views.edit_profile, name="edit_profile"),
    path('profile/password', views.change_password, name="change_password"),
    path('maps', views.maps, name='maps'),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('detail/<slug:slug>', views.news_detail, name="detail"),
    path('categories/<int:id>/', views.news_category, name="category"),
    path('categories/<int:id>/<slug:slug>', views.news_category_detail, name="category_detail"),
]

templates/_messages.html
{# django messages #}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}secondary{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include './nav.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}
</body>
</html>

templates/change_password.html
{% extends './base.html' %}
{% block title %}เปลี่ยนรหัสผ่าน{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col offset-1">
            <h1>เปลี่ยนรหัสผ่าน</h1>
            {# show messages #}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            {# form #}
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="old_password">รหัสผ่านเดิม</label>
                    <input type="password" name="old_password" id="old_password" class="form-control" aria-describedby="passwordHelpBlock">
                    <small id="passwordHelpBlock" class="form-text text-muted">
                        Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
                    </small>
                </div>
                <div class="form-group">
                    <label for="new_password">รหัสผ่านใหม่</label>
                    <input type="password" name="new_password" id="new_password" class="form-control" aria-describedby="passwordHelpBlock">
                    <small id="passwordHelpBlock" class="form-text text-muted">
                        Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
                    </small>
                </div>
                <div class="form-group">
                    <label for="confirm_password">ยีนยันรหัสผ่านใหม่</label>
                    <input type="password" name="confirm_password" id="confirm_password" class="form-control" aria-describedby="passwordHelpBlock">
                    <small id="passwordHelpBlock" class="form-text text-muted">
                        Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
                    </small>
                </div>

                <button type="submit" class="btn btn-warning">เปลี่ยนรหัสผ่าน</button>
                <a href="{% url 'covid:edit_profile' %}" class="button mx-3">ยกเลิก</a>
            </form>

        </div>
    </div>
{% endblock content %}

templates/edit_profile.html
{% extends './base.html' %} 
{% load crispy_forms_tags %}

{% block title %}แก้ไขข้อมูล{% endblock title %}

{% block content %}
    <h1>แก้ไขข้อมูลส่วนตัวของ {{ user.username }}</h1>
    <br>
    
    <div class="container">
    
        <form action="" method="post">
    
            {% csrf_token %}
            <table>
                {{ form|crispy }}
            </table>
    
            <button type="submit" class="btn btn-primary inline-block mx-3">อัพเดทข้อมูล</button>
            <a href="{% url 'covid:change_password' %}" class="button button-primary inline-block mx-3">เปลี่ยนรหัสผ่าน</a>
    
        </form>
    </div>


{% endblock content %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark border-bottom shadow-sm mb-5">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="navbar-brand" href="{% url 'covid:home' %}"><img src="{% static 'img/icon.png' %}" width="35" height="35" class="d-inline-block align-top" alt="navbar">
                    Coronavirus Risk Assessment
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'covid:home' %}">หน้าหลัก</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'covid:assessment' %}">คำถามประเมินความเสี่ยง</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'news:home' %}">ข่าวสาร</a>
            </li>

            {# check login #}
            {% if user.is_authenticated %}
                <li class="nav-item active mx-2">
                    <a class="nav-link" href="{% url 'covid:profile' %}">สวัสดี, <span class="font-weight-bold">{{ request.user.username }}</span></a>
                </li>

                {# check staff #}
                {% if user.is_staff %}
                    <li class="nav-item active">
                        <li class="nav-item active mx-2 bg-info card">
                            <a class="nav-link" href="http://127.0.0.1:8000/admin/" target="_blank">ผู้ดูแลระบบ</a>
                        </li>
                    </li>
                {% endif %}

                <li class="nav-item active">
                    <form action="{% url 'covid:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">ออกจากระบบ</button>
                    </form>
                </li>

            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'covid:register' %}">สมัครสมาชิก</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'covid:login' %}">เข้าสู่ระบบ</a>
                </li>
                
            {% endif %}
        </ul>
    </div>
</nav>

templates/profile.html
{% extends './base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Profile{% endblock title %}

{% block content %}
{% include './_messages.html' %}
{% if msg %}
    <div class="alert alert-info text-center w-100">
        <button type="button" class="close span" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ยินดีต้อนรับ <b>{{ user.username }}</b>
    </div>
{% endif %}
    <div class="card shadow-sm">
        <div class="card-body">
            <div class="row">
                <div class="col-3">
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        <h2>โปรไฟล์ของฉัน</h2>
                        <img src="{% static 'img/doctor-suit-full.png' %}" alt="profile-img" class="img-thumbnail w-50 border-0">
                        <div class="list-group my-2 w-100">
                            <a href="{% url 'covid:profile' %}" class="list-group-item list-group-item-action active py-1">ประวัติการประเมิน</a>
                            <a href="{% url 'covid:edit_profile' %}" class="list-group-item list-group-item-action py-1">ข้อมูลของฉัน</a> 
                            {% comment %} <a href="#" class="list-group-item list-group-item-action py-1">My Map</a>  {% endcomment %}
                            <div class="my-3 mt-4">
                                <form action="{% url 'covid:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm">ออกจากระบบ</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col border-left px-4">
                    {% comment %} <h1>ประวัติ</h1> {% endcomment %}
                    <table class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="text-center">ครั้งที่</th>
                                <th scope="col" class="text-center">ผลลัพธ์</th>
                                <th scope="col">สร้างเมื่อ</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if user_history %}
                                {% for i in user_history %}
                                    <tr>
                                        <th class="text-center">{{ forloop.revcounter }}</th>
                                        <td class="text-center">
                                            {% if i.prediction_result == '1' %}
                                                <p class="text-center text-warning">มีความเสี่ยง</p>
                                            {% else %}
                                                <p class="text-center text-success">ไม่มีความเสี่ยง</p>
                                            {% endif %}
                                        </td>
                                        <td>{{ i.created|naturaltime }} ({{ i.created }}) </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $('.alert').alert('close');
    </script>
{% endblock content %}