backend/urls.py
from django.contrib import admin
from django.urls import path, include

# media upload
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('covid.urls', 'covid'), namespace='covid')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

covid/urls.py
from django.urls import path
from covid import views

urlpatterns = [
    path('', views.index, name = 'home'),
    path('predict', views.predict, name='predict'),
    path('saveresult', views.saveResult, name="saveresult"),
    path('confirm', views.confirm, name='confirm'),
    path('assessment', views.assessment, name='assessment'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name="profile"),
    path('profile/edit', views.edit_profile, name="edit_profile"),
    path('profile/password', views.change_password, name="change_password"),
    path('maps', views.maps, name='maps'),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('detail/<slug:slug>', views.news_detail, name="detail"),
    path('categories/<int:id>/', views.news_category, name="category"),
    path('categories/<int:id>/<slug:slug>', views.news_category_detail, name="category_detail"),
]

covid/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
class UserInfo(models.Model):
    RISK_LEVEL = (
        ('1', 'เสี่ยงระดับ 1'),
        ('2', 'เสี่ยงระดับ 2'),
        ('3', 'เสี่ยงระดับ 3'),
    )

    code = models.IntegerField(verbose_name="User Code", unique=1)
    fname = models.CharField(verbose_name="firstname", max_length=255)
    lname = models.CharField(verbose_name="lastname", max_length=255)
    email = models.EmailField(verbose_name="E-Mail", max_length=254)
    phone = models.CharField(max_length=10)
    risk_lv = models.CharField("Risk Level", max_length=20, choices=RISK_LEVEL, default=RISK_LEVEL[0][1])

    class Meta:
        verbose_name_plural = "User Information"
    
    def __str__(self):
        return self.fname
    

class TypePredict(models.Model):
    p_name = models.CharField(verbose_name="predict name", max_length=200)
    created = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        verbose_name_plural = "Type of Prediction Result"
    
    def __str__(self):
        return self.p_name
    
class UserHistory(models.Model):
    u_id = models.CharField(verbose_name="USER ID", max_length=10)
    prediction_result = models.CharField(verbose_name="result of prediction", max_length=10)
    created = models.DateTimeField(auto_now=True, auto_now_add=False)
    
    class Meta:
        verbose_name_plural = "User History"
    
    # def ShowUserName(self):
    #     if self.u_id:
    #         user = User.objects.get(id=u_id)
    #         return user.username
    #     return '--'

    def __str__(self):
        return self.prediction_result
    

covid/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from covid.forms import RegisterForm, EditProfileForm, UserLoginFormTH
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth.decorators import login_required
# from sklearn import tree
# from sklearn.model_selection import train_test_split
# import pandas as pd
import requests as rq
from datetime import datetime, date
from geopy.geocoders import Nominatim
from .models import *
from .forms import UserHistoryForm
from django.contrib.auth.models import User
from django.contrib import messages

# from sklearn.svm import SVC

# Create your views here.
def index(request):
    # r = rq.get('https://covid19.th-stat.com/json/covid19v2/getTodayCases.json')
    # print("[HTTP Status of COVD-19 API]: {}".format(r.status_code))
    # print('[USER LOGIN] ',request.user.is_authenticated)
    # print('[USER ID]',request.user.id)
    # if r.status_code == 200:
    #     data = r.json()
    #     dt = datetime.strptime(data['UpdateDate'], "%d/%m/%Y %H:%M").date() #  datetime = "xx/xx/xxxx xx:xx" + date() = "xx/xx/xxxx"
    
    #     context = {
    #         # sent each data from API to templates
    #         'confirmedCase':data['Confirmed'],
    #         'recoveredCase':data['Recovered'],
    #         'hospitalizedCase':data['Hospitalized'],
    #         'deathCase':data['Deaths'],
    #         'newConfirmed':data["NewConfirmed"],
    #         'newRecovered':data["NewRecovered"],
    #         'newHospitalized':data["NewHospitalized"],
    #         'newDeaths':data["NewDeaths"],
    #         'updateDate': dt,
    #         'updateDate2': data['UpdateDate']
    #     }
    # # 404 etc.
    # else:
    #     context = {
    #         # sent each data from API to templates
    #         'confirmedCase': "__",
    #         'recoveredCase': "__",
    #         'hospitalizedCase': "__",
    #         'deathCase': "__",
    #         'newConfirmed': "__",
    #         'newRecovered': "__",
    #         'newHospitalized': "__",
    #         'newDeaths': "__",
    #         'updateDate': "__",
    #     }
    context = {
        # sent each data from API to templates
        'confirmedCase': "__",
        'recoveredCase': "__",
        'hospitalizedCase': "__",
        'deathCase': "__",
        'newConfirmed': "__",
        'newRecovered': "__",
        'newHospitalized': "__",
        'newDeaths': "__",
        'updateDate': "__",
        }
    return render(request, 'covid/index.html', context)

@login_required
def predict(request):
    # dataset
    # dataset_covid = pd.read_csv('https://raw.githubusercontent.com/Nattawut-M/my_csv/main/DATASET_v4.csv')
    # # select attribute 
    # x = dataset_covid[['a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18','a19','a20']]
    # # selected label/target
    # y = dataset_covid['result'] 
    # # processing 
    # train_x, test_x, train_y, test_y = train_test_split(x, y, train_size = 0.8)
    # tree_model = tree.DecisionTreeClassifier()
    # tree_model = tree_model.fit(train_x, train_y)
    # tree_score = tree_model.score(test_x, test_y)


    # if submit form 'POST' 
    if request.method == 'POST':
        form = UserHistoryForm()
        ans = []
        userLocation = []
        for i, value in request.POST.items():
            # seperate 'csrf_token', 'latitude', 'longitude' (only data question)
            print('[index] {}, Ans: {}'.format(i, value))
            if i != 'csrfmiddlewaretoken' and i != 'latitude' and i != 'longitude':
                ans.append(value)

        # assign address to variable
        if request.POST['latitude'] and request.POST['longitude']:
            userLocation = [request.POST.get('latitude'), request.POST.get('longitude')]
            # geopy
            geomap = Nominatim(user_agent="MapInfo")
            geolocation = geomap.reverse("{},{}".format(userLocation[0], userLocation[1])) # search
            geoAddress = geolocation.raw['address'] # assign value of raw['address] to variable 'geoAddress' then assign to each variable(area, district, province, country)
            area = geoAddress.get('town','-')
            district = geoAddress.get('county', '-')
            province = geoAddress.get('state', '-')
            country = geoAddress.get('country', '-')
        else:
            # not found latitude and longitude
            area = '-'
            district = '-'
            province = '-'
            country = '-'

        

        print('[Question Answer]:  {}'.format(ans))
        print('[LOCATION]:  {}'.format(userLocation))

        # PREDICTION VALUES
        # result = tree_model.predict([ans])
        # print('[RESULT]\n- type:{} ({})% type: {}'.format(result, (tree_score*100), type(result)))
        # result = result.tolist()
        # # ans_result = result.pop()
        # # print('[result.pop()]: {}'.format(result.pop()))
        # print('[Type of \'toList()\'] : \t{0}'.format(result.pop()))

        # logic tree prediction from rapidminer studio
        if request.POST['question19'] == '1':
            ans_result = 1
            print('question:19 = 1')
        else:
            if request.POST['question18'] == '1':
                ans_result = 1
                print('question:18 = 1')
            else:
                if request.POST['question20'] == '1':
                    if request.POST['question2'] == '1':
                        ans_result = 1
                        print('question:20 & 2 = 1')
                    else:
                        if  request.POST['question11'] == '1':
                            ans_result = 1
                            print('question:11 = 1')
                        else:
                            if request.POST['question4'] == '1':
                                ans_result = 1
                                print('question:4 = 1')
                            else:
                                ans_result = 0
                                print('question:4 = 0')
                else:
                    if  request.POST['question1'] == '1':
                        ans_result = 1
                        print('question:1 = 1')
                    else:
                        if  request.POST['question5'] == '1':
                            if  request.POST['question2'] == '1':
                                ans_result = 1
                                print('question:5 & 2 = 1')
                            else:
                                ans_result = 0
                                print('question:2 = 0')
                        else:
                            ans_result = 0
                            print('question:5 = 0')

        
    riskType = [
        1*(100/3),
        2*(100/3),
        3*(100/3)
    ]
    geomap = [
        area,
        district,
        province,
        country
    ]
    context =  {
        'result': ans_result,
        # 'score': tree_score,
        # 'score': svc_score,
        'userLocation': userLocation,
        'riskType': riskType,
        'geomap':geomap,
        'form':form
    }
    return render(request, 'covid/predict1.html', context)

def saveResult(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserHistoryForm(data=request.POST)
        if form.is_valid():
            form.save(commit=True)
            print('\n\n\n[COMMIT Form] :\t SUCCESSFULLY\n\n\n')
            messages.success(request, "บันทึกผลสำเร็จ")
            return redirect('covid:home')
        else: 
            print('\n\n\n*****[error]*****')
            print(f'[form.is_valid()]:\t{form.is_valid()}\n\n\n')

    return redirect('covid:home')

@login_required
def assessment(request):
    return render(request, 'covid/form_assessment.html')


def confirm(request):
    return render(request, 'covid/confirm.html')


def register(request):
    if request.method == 'POST':

        # check data from POST method
        for i, j in enumerate(request.POST):
            print(i,j)
        
        # change username from Case-Sensitive to lowercase 
        # set mutable before using lowercase 'lower()'
        # request.POST and request.GET will be immutable when accessed in a normal request/response cycle.
        # [FIXED-1] https://stackoverflow.com/questions/44717442/this-querydict-instance-is-immutable
        # [EXPLAIN-1] https://stackoverflow.com/questions/12611345/django-why-is-the-request-post-object-immutable
        print(request.POST['username']) # check before lowercase
        username_case = request.POST['username']
        request.POST._mutable = True # mutable = ค่าเปลี่ยนแปลงได้
        request.POST['username'] = username_case.lower() # set username to lowercase using method 'lower()'
        request.POST._mutable = False
        print(request.POST['username']) # check after lowercase

        # register User 
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save(commit=1)
            messages.success(request, "สมัครสมาชิกสำเร็จ โปรดเข้าสู่ระบบเพื่อใช้งาน")
            request.session['msg_type'] = "success"
            return redirect('covid:login')
    else:
        form = RegisterForm()
    return render(request, 'covid/register.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        print("[request.POST]\t {}; with Loop {}".format(request.POST, len(request.POST)))
        for i in request.POST:
            print(i)
        loginForm = UserLoginFormTH(data=request.POST)
        next_url = request.GET.get('next') # save page want to visit, but has not login
        print(next_url)
        if loginForm.is_valid():
            user = loginForm.get_user()
            request.session['has_visit'] = False # default 'visit profile' page

templates/covid/confirm.html

{% extends '../base.html' %}

{% load static %}

{% block title %}Confirm{% endblock title %}

{% block content %}

    <div class="d-flex justify-content-center align-items-center mt-5">
        <div class="row mt-5 pt-5">
            <div class="col">
                <img src="{% static 'img/doctor-suit-full.png' %}"  class="img-fluid">
            </div>
            <div class="col align-self-center">
                <div class="card-body">
                    <center><h1>แบบฟอร์มประเมินความเสี่ยง COVID-19 ด้วยตนเองเบื้องต้น</h1><br>
                    <p>แบบฟอร์มนี้เป็นการประเมินความเสี่ยงเพียงเบื้องต้นโดยการประเมินนี้มีการเก็บข้อมูลโดยไม่ระบุตัวตนและโปรดอนุญาตให้เว็บไซต์นี้เข้าถึงตำแหน่งของท่านโดยการประเมินนี้มีการเก็บข้อมูลโดยไม่ระบุตัวตนและโปรดอนุญาตให้เว็บไซต์นี้เข้าถึงตำแหน่งของท่าน</p>
                    
                    <p id="demo"></p>
                    <script>
                        var x = document.getElementById("demo");
                        
                        function getLocation() {
                        if (navigator.geolocation) {
                            navigator.geolocation.getCurrentPosition(showPosition);
                        } else { 
                            x.innerHTML = "Geolocation is not supported by this browser.";
                        }
                        }
                        
                        function showPosition(position) {
                        x.innerHTML = "Latitude: " + position.coords.latitude + 
                        "<br>Longitude: " + position.coords.longitude;
                        }
                    </script>
                    
                    <form action="{% url 'covid:assessment' %}">
                        <input type="checkbox" onclick="getLocation()" id="myCheck" name="test" required>
                        <span class="m-2">ฉันยอมรับและอนุญาตให้เข้าถึงตำแหน่ง</span>
                        <input a class="btn btn-primary my-2" type="submit" value="ทำแบบประเมินความเสี่ยง COVID-19">
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

templates/covid/index.html
{% load static %}
{% load humanize %}
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>COVID-19</title>
</head>
<body>
    {% include '../nav.html' %}
        <div class="container mt-5 pt-3">
        {% include '../_messages.html' %}
            <div class="row mb-1">
                <div class="col">
                    <h2 class="text-center">เว็บประเมินความเสี่ยงโรคไวรัสโคโรนาสายพันธุ์ใหม่โดยเทคนิคการทำเหมืองข้อมูล</h2><br>
                </div>
            </div>
    
            <div class="row">
                {# image #}
                <div class="col-5 mt-5">
                    <div class="row">
                        <div class="col-10">
                            <h4 class="mb-0 text-center my-1">ยอดรวมผู้ติดเชื้อในประเทศไทย</h4>
                            <p class="text-weight-light text-center mb-0">
                                {% comment %}
                                {% if updateDate|naturalday != 'today' %}
                                        อัพเดทล่าสุดเมื่อ: <b>{{ updateDate2 }} น.</b>
                                {% else %}
                                        อัพเดทล่าสุด: <b>{{ updateDate2 }} น. (วันนี้)</b>
                                {% endif %}
                                     อัพเดทล่าสุดเมื่อ <b>6 &nbsp;มิ.ย. 2564 เวลา 12.30 น.</b>
                                {% endcomment %}
                                <span id="UpdateDate"></span>&nbsp;น.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <img class="img-fluid p-4 h-75 m-0" src="{% static 'img/index.png' %}">
                        </div>
                    </div>
                </div>

                {# dashboard #}
                <div class="col py-3">
                    <div class="mt-5">
                        <div class="mb-5">
                            <div class="row">
                                <div class="col">
                                    <div class="row">
                                        <div class="col-sm-12 mx-auto">
                                            <div class="card text-center text-white bg-primary mb-3">
                                                <div class="card-body">
                                                    <h2 class="card-title">ยอดผู้ติดเชื้อสะสม</h2>
                                                    {% comment %}<h3 class="card-text">{{ confirmedCase|intcomma }} คน</h3>{% endcomment %}
                                                    <h3 class="card-text"><span id="Confirmed"></span> คน</h3>
                                                    <a href="#" class="btn btn-light">
                                                        <span id="NewConfirmed"></span>
                                                        {% comment %}
                                                        {% if newConfirmed > 0 %}
                                                            <span class="text-danger"><b><u>เพิ่มขึ้น</u></b></span> {{ newConfirmed|intcomma }} คน
                                                        {% else %}
                                                            <span class="text-success"><b><u>ลดลง</u></b></span> {{ newConfirmed|intcomma }} คน
                                                        {% endif %}
                                                        {% endcomment %}

                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    
                            <div class="row">
                                <div class="col">
                                    <div class="card">
                                        <div class="card text-center text-white bg-warning">
                                            <div class="card-body">
                                                <h5 class="card-title">กำลังรักษา</h5>
                                                {% comment %} <h5 class="card-text">{{ hospitalizedCase|intcomma }} คน</h5> {% endcomment %}
                                                <h5 class="card-text"><span id="Hospitalized"></span> คน</h5>
                                                <a href="#" class="btn btn-light">
                                                    <span id="NewHospitalized"></span>
                                                    {% comment %}
                                                    {% if newHospitalized > 0 %}
                                                        <span class="text-danger"><b><u>เพิ่มขึ้น</u></b></span> {{ newHospitalized|intcomma }}  คน
                                                    {% elif newHospitalized == 0 %}
                                                        <span class="text-warning"><b><u>คงที่</u></b></span> {{ newHospitalized|intcomma }}  คน
                                                    {% else %}
                                                        <span class="text-success"><b><u>ลดลง</u></b></span> {{ newHospitalized|abs }} คน
                                                    {% endif %}
                                                    {% endcomment %}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col">
                                    <div class="card">
                                        <div class="card text-center text-white bg-success">
                                            <div class="card-body">
                                                <h5 class="card-title">รักษาหายแล้ว</h5>
                                                {% comment %} <h5 class="card-text">{{ recoveredCase|intcomma }} คน</h5> {% endcomment %}
                                                <h5 class="card-text"><span id="Recovered"></span> คน</h5>
                                                <a href="#" class="btn btn-light">
                                                    <span id="NewRecovered"></span>
                                                    {% comment %} 
                                                    {% if newRecovered > 0 %}
                                                        <span class="text-success"><b><u>เพิ่มขึ้น</u></b></span> {{ newRecovered|intcomma }} คน
                                                    {% else %}
                                                        {{ newRecovered|intcomma }} คน
                                                    {% endif %}
                                                     {% endcomment %}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col">
                                    <div class="card">
                                        <div class="card text-center text-white bg-danger">
                                            <div class="card-body">
                                                <h5 class="card-title">เสียชีวิต</h5>
                                                {% comment %} <h3 class="card-text">{{ confirmedCase|intcomma }} คน</h3> {% endcomment %}
                                                <h5 class="card-text"><span id="Deaths"></span> คน</h5>
                                                <a href="#" class="btn btn-light"><span id="NewDeaths"></span> คน</a>
                                                {% comment %}
                                                {% if newDeaths > 0 %}
                                                    <a href="#" class="btn btn-light"><span class="text-danger"><b><u>เพิ่มขึ้น</u></b></span> {{ newDeaths|intcomma }} คน</a>
                                                {% elif newDeaths == 0 %}
                                                    <a href="#" class="btn btn-light"><span class="text-danger"><b><u>คงที่</u></b></span> {{ newDeaths|intcomma }} คน</a>
                                                {% else %}
                                                    <span class="btn btn-light text-success"><b><u>ลดลง</u></b></span> {{ newDeaths|abs }} คน
                                                {% endif %}
                                                {% endcomment %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col">
                                    <div class="card bg-dark py-2">
                                        <a class="btn btn-block text-white" href="{% url 'covid:assessment' %}">
                                            ทำแบบประเมินความเสี่ยง
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
<!-- Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    axios.get('https://covid19.th-stat.com/json/covid19v2/getTodayCases.json').then((result) => {
        // Date
        document.getElementById("UpdateDate").innerHTML = result.data["UpdateDate"];
        // Total Case
        document.getElementById("Confirmed").innerHTML = result.data["Confirmed"];
        document.getElementById("Hospitalized").innerHTML = result.data["Hospitalized"];
        document.getElementById("Recovered").innerHTML = result.data["Recovered"];
        document.getElementById("Deaths").innerHTML = result.data["Deaths"];
        // Update Case
        document.getElementById("NewConfirmed").innerHTML = result.data["NewConfirmed"];
        document.getElementById("NewHospitalized").innerHTML = result.data["NewHospitalized"];
        document.getElementById("NewRecovered").innerHTML = result.data["NewRecovered"];
        document.getElementById("NewDeaths").innerHTML = result.data["NewDeaths"];
    }).catch((err) => {
        console.log(err);
    });
</script>
</html>

templates/covid/predict1.html
{% extends '../base.html' %}

{% load static %}
{% load mathfilters %}

{% block title %}Prediction{% endblock title %}
{% block content %}
    <div class="container card py-4">
        <div class="row d-flex justifiy-content-around align-items-stretch">
            <div class="img  border-right">
                <div class="col mt-5">
                    <img src="{% static 'img/doctor-suit.png' %}"  width="400" height="400">
                </div>
            </div>
            
            <div class="col px-3 pt-3">
                <div class="font mt-4">
                    <h4 class='text-center'>ผลการประเมินความเสี่ยง COVID-19 ด้วยตนเองเบื้องต้น</h4>
                    <p class='text-center mb-4'>ความเสี่ยงของท่านอยู่ในเกณฑ์ : </p>

                    {% if result == 2 %}
                        <strong class="text-center text-danger">ท่านมีความเสี่ยงระดับ 2 ({{ score|mul:100|floatformat:1 }}%)</strong>
                    {% elif result == 1 %}
                        <p class="text-center text-warning">ท่านอาจมีความเสี่ยงในติดเชื้อ COVID <strong>**โปรดตรวจที่โรงพยาบาลเพื่อยืนยันอีกครั้ง**</strong> </p>
                    {% else %}
                        <p class="text-center text-success">ท่านไม่มีความเสี่ยงติดเชื้อ COIVD <strong>**โปรดตรวจที่โรงพยาบาลเพื่อยืนยันอีกครั้ง** </strong></p>
                    {% endif %}
                    

                    <div class="progress mb-3" style="height: 30px;">
                        {% if result == 2 %}
                            <div class="progress-bar bg-danger" role="progressbar" style="width:{{ riskType.2 }}%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">ไม่มีความเสี่ยง</div>
                        {% elif result == 1 %}
                            <div class="progress-bar bg-warning" role="progressbar" style="width:{{ riskType.1 }}%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">มีความเสี่ยง</div>
                        {% else %}
                            <div class="progress-bar bg-success" role="progressbar" style="width:{{ riskType.0 }}%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">ไม่มีความเสี่ยง</div>
                        {% endif %}
                    </div>

                    <div class="container my-4 border-bottom">
                        {% if geomap %}
                            <p class="font-weight-normal"><b>บริเวณพื้นที่:</b> {{ geomap.0 }}</p>
                            <p class="font-weight-normal"><b>อำเภอ:</b> {{ geomap.1 }}</p>
                            <p class="font-weight-normal"><b>จังหวัด:</b> {{ geomap.2 }}</p>
                            <p class="font-weight-normal"><b>ประเทศ:</b> {{ geomap.3 }}</p>
                        {% endif %}
                    </div>

                    {% comment %} <div class="icon">
                        <i class="fa fa-caret-up" style="font-size:60px"></i>
                    </div> {% endcomment %}

                    <div class="container d-flex justify-content-between">
                        <form action="{% url 'covid:saveresult' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="u_id" maxlength="10" required id="id_u_id" value="{{ user.id }}">
                            <input type="hidden" name="prediction_result" maxlength="10" required id="id_prediction_result" value="{{ result }}">
                            <button type="submit" class="btn btn-primary mx-4">บันทึกผลการประเมิน</button>
                            <a href="{% url 'covid:home' %}" class="btn btn-dark">ไม่บันทึก</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}